# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  adapter: postgresql
  encoding: unicode
  database: platform_evenimente_development
  pool: 5
  username: rth
  password: rth

test:
  adapter: postgresql
  encoding: unicode
  database: platform_evenimente_test
  pool: 5
  username: rth
  password: rth

production:
  primary: &primary_production
    <<: *default
    database: proiect_production
    username: proiect
    password: <%= ENV["PROIECT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: proiect_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: proiect_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: proiect_production_cable
    migrations_paths: db/cable_migrate
